name: sc-notebook
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - attrs=19.3.0
  - backcall=0.2.0
  - beautifulsoup4=4.9.1
  - blas=1.0
  - bleach=3.1.5
  - boto=2.49.0
  - boto3=1.16.30
  - botocore=1.19.30
  - brotlipy=0.7.0
  - ca-certificates=2020.10.14
  - cachetools=4.1.1
  - certifi=2020.12.5
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.2
  - cryptography=2.9.2
  - cycler=0.10.0
  - dbus=1.13.16
  - decorator=4.4.2
  - defusedxml=0.6.0
  - docutils=0.15.2
  - entrypoints=0.3
  - expat=2.2.9
  - flashtext=2.7
  - fontconfig=2.13.0
  - freetype=2.10.2
  - gensim=3.8.0
  - glib=2.65.0
  - google-api-core=1.22.2
  - google-auth=1.21.3
  - google-cloud-core=1.4.4
  - google-cloud-storage=1.31.0
  - google-crc32c=1.0.0
  - google-resumable-media=1.1.0
  - googleapis-common-protos=1.52.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - icu=58.2
  - idna=2.10
  - importlib-metadata=1.7.0
  - importlib_metadata=1.7.0
  - inflect=5.0.2
  - intel-openmp=2020.1
  - ipykernel=5.3.0
  - ipython=7.16.1
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.1
  - jinja2=2.11.2
  - jmespath=0.10.0
  - joblib=0.17.0
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.5
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - kiwisolver=1.2.0
  - ld_impl_linux-64=2.33.1
  - libcrc32c=1.1.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - libuuid=1.0.3
  - libxcb=1.14
  - libxml2=2.9.10
  - markupsafe=1.1.1
  - matplotlib=3.2.2
  - matplotlib-base=3.2.2
  - mistune=0.8.4
  - mkl=2020.1
  - mkl-service=2.3.0
  - mkl_fft=1.1.0
  - mkl_random=1.1.1
  - nbconvert=5.6.1
  - nbformat=5.0.7
  - ncurses=6.2
  - nltk=3.5
  - notebook=6.0.3
  - numpy=1.18.5
  - numpy-base=1.18.5
  - openssl=1.1.1h
  - packaging=20.4
  - pandas=1.0.5
  - pandoc=2.9.2.1
  - pandocfilters=1.4.2
  - parso=0.7.0
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.1.1
  - prometheus_client=0.8.0
  - prompt-toolkit=3.0.5
  - prompt_toolkit=3.0.5
  - protobuf=3.13.0.1
  - ptyprocess=0.6.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pygments=2.6.1
  - pyopenssl=19.1.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysocks=1.7.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - pytz=2020.1
  - pyzmq=19.0.1
  - qt=5.9.7
  - qtconsole=4.7.5
  - qtpy=1.9.0
  - readline=8.0
  - regex=2020.11.13
  - requests=2.24.0
  - rsa=4.6
  - s3transfer=0.3.3
  - scikit-learn=0.23.2
  - scipy=1.5.0
  - seaborn=0.10.1
  - send2trash=1.5.0
  - setuptools=47.3.1
  - sip=4.19.8
  - six=1.15.0
  - smart_open=4.0.1
  - soupsieve=2.0.1
  - sqlite=3.32.3
  - terminado=0.8.3
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tk=8.6.10
  - tornado=6.0.4
  - traitlets=4.3.3
  - urllib3=1.25.9
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xz=5.2.5
  - zeromq=4.3.2
  - zipp=3.1.0
  - zlib=1.2.11
  - pip:
    - appdirs==1.4.4
    - bs4==0.0.1
    - contractions==0.0.43
    - cssselect==1.1.0
    - dnspython==2.0.0
    - fake-useragent==0.1.11
    - lxml==4.5.2
    - parse==1.15.0
    - pyahocorasick==1.4.0
    - pyee==7.0.2
    - pymongo==3.11.0
    - pyppeteer==0.2.2
    - pyquery==1.4.1
    - python-dotenv==0.14.0
    - textsearch==0.0.17
    - tqdm==4.47.0
    - unidecode==1.1.1
    - w3lib==1.22.0
    - websockets==8.1

