name: sc-notebook
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.6
  - jupyter
  - pandas
  - matplotlib
  - seaborn
  - nltk
  - inflect
  - scikit-learn
  - gensim
  - networkx
  - pygraphviz
  - pip:
    - beautifulsoup4
    - contractions
    - dnspython
    - pymongo
    - demjson
    - python-dotenv
    - tqdm
    - grequests
